<a href="https://colab.research.google.com/github/FarabiOnAMission/Machine-Learning-Stuffs/blob/main/DigitRecognizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('train.csv')

In [ ]:
dataset.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [ ]:
dataset = np.array(dataset)
m, n = dataset.shape
np.random.shuffle(dataset)

test_set = dataset[0:1000].T
Y_test = test_set[0]
X_test = test_set[1:n]/255

train_set = dataset[1000:m].T
Y_train = train_set[0]
X_train = train_set[1:n]/255

In [ ]:
def _init_params():
  W1 = np.random.rand(128,784) - 0.5
  b1 = np.random.rand(128,1) - 0.5
  W2 = np.random.rand(10,128) - 0.5
  b2 = np.random.rand(10,1) - 0.5

  return W1,b1,W2,b2

def ReLU(Z):
  return np.maximum(0,Z)

def softmax(Z):
  return np.exp(Z)/np.sum(np.exp(Z),axis=0,keepdims=True)

def forward_prop(W1,b1,W2,b2,X):
  Z1 = W1.dot(X) + b1
  A1 = ReLU(Z1)
  Z2 = W2.dot(A1) + b2
  A2 = softmax(Z2)
  return Z1, A1, Z2, A2

def one_hot(Y):
  one_hot_Y = np.zeros((Y.max() + 1,Y.size))
  one_hot_Y[Y,np.arange(Y.size)] = 1
  return one_hot_Y

def deriv_ReLU(Z):
  return Z > 0

def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
  m= Y.size
  one_hot_Y = one_hot(Y)
  dZ2 = A2 - one_hot_Y
  dW2 = 1/m * dZ2.dot(A1.T)
  db2 = 1 / m * np.sum(dZ2, 1, keepdims=True)
  dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
  dW1 = 1/m * dZ1.dot(X.T)
  db1 = 1/m * np.sum(dZ1,1,keepdims=True)
  return dW1, db1, dW2, db2

def update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha):
  W1 = W1 - alpha * dW1
  b1 = b1 - alpha * db1
  W2 = W2 - alpha * dW2
  b2 = b2 - alpha * db2
  return W1,b1,W2,b2



In [ ]:
def get_predictions(A2):
  return np.argmax(A2,0)

def get_accuracy(predictions,Y):
  print(predictions,Y)
  return np.sum(predictions == Y)/Y.size

def gradient_descent(X,Y,alpha,iterations):
  W1,b1,W2,b2 = _init_params()
  for i in range(iterations):
    Z1,A1,Z2,A2 = forward_prop(W1,b1,W2,b2,X)
    dW1,db1,dW2,db2= back_prop(Z1,A1,Z2,A2,W1,W2,X,Y)
    W1,b1,W2,b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)

    if(i%10 == 0):
      print("Iteration: ", i)
      predictions = get_predictions(A2)
      print("Accuracy: ",get_accuracy(predictions,Y))
  return W1,b1,W2,b2

In [ ]:
W1 , b1 , W2, b2 = gradient_descent(X_train,Y_train, 0.1 , 1000)

Iteration:  0
[4 2 2 ... 9 2 9] [5 9 5 ... 0 5 8]
Accuracy:  0.09019512195121951
Iteration:  10
[5 5 5 ... 0 5 1] [5 9 5 ... 0 5 8]
Accuracy:  0.5194390243902439
Iteration:  20
[5 5 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.6549512195121951
Iteration:  30
[5 4 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.7143170731707317
Iteration:  40
[5 4 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.748390243902439
Iteration:  50
[5 4 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.770219512195122
Iteration:  60
[5 9 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.7878536585365854
Iteration:  70
[5 9 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.8017804878048781
Iteration:  80
[5 9 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.8118048780487805
Iteration:  90
[5 9 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.8211219512195121
Iteration:  100
[5 9 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.8279756097560975
Iteration:  110
[5 9 5 ... 0 5 9] [5 9 5 ... 0 5 8]
Accuracy:  0.8341219512195122
Iteration:  120
[5 9 5 ... 0

In [ ]:
_, _, _, A2_test = forward_prop(W1, b1, W2, b2, X_test)
test_predictions = get_predictions(A2_test)
print("Test Set Accuracy: ", get_accuracy(test_predictions, Y_test)*100)

[1 4 2 3 0 4 8 1 9 9 0 5 0 2 3 5 8 0 7 7 6 8 4 2 2 1 2 8 8 1 1 8 3 6 7 1 4
 8 3 7 4 3 6 9 9 1 5 1 6 6 4 8 4 2 1 3 9 2 9 1 2 3 5 6 8 1 9 2 2 2 6 6 9 5
 5 6 8 9 0 0 5 5 3 9 3 9 0 0 1 1 6 7 6 9 1 0 0 0 2 6 2 9 6 3 4 6 9 1 3 7 3
 9 7 6 8 8 2 4 2 6 7 7 2 4 6 4 4 0 3 2 1 4 1 7 7 3 8 8 5 0 5 2 4 7 0 3 7 5
 7 1 7 5 5 3 5 7 8 9 0 2 2 4 4 8 3 0 4 0 4 4 5 4 3 0 6 4 1 4 7 2 5 0 1 7 8
 9 7 7 7 4 9 8 5 8 5 3 6 8 3 9 9 9 6 4 1 7 8 2 1 6 4 5 7 0 7 3 3 9 5 6 9 7
 1 3 0 7 0 8 9 7 8 2 1 0 8 4 6 2 7 7 4 9 5 1 1 0 9 7 4 8 9 3 7 8 7 0 5 9 6
 4 8 9 9 5 5 4 7 2 2 9 9 0 4 5 2 8 1 0 0 6 7 1 6 8 0 3 6 5 8 9 9 1 5 9 3 7
 3 3 1 2 4 3 3 4 2 6 1 1 9 6 5 6 1 9 1 9 7 3 0 0 9 3 8 5 6 3 6 3 3 9 8 8 5
 1 3 8 3 3 9 5 1 0 1 8 5 3 3 4 7 8 9 7 5 2 8 6 4 6 5 5 6 0 3 3 9 5 6 1 5 3
 0 7 4 1 1 6 8 0 8 7 1 1 7 6 6 3 4 2 5 4 8 0 9 6 2 9 5 3 6 4 5 7 0 8 5 6 6
 2 5 9 6 1 3 0 8 0 3 0 7 2 5 7 9 8 3 6 3 7 9 6 7 0 9 9 9 2 8 7 8 0 1 9 8 8
 1 0 7 4 7 9 7 0 6 6 0 5 7 2 6 8 4 1 4 8 2 1 3 3 8 7 0 1 6 3 8 0 7 8 9 3 9
 1 8 1 0 7 1 9 8 9 7 5 5 